AWSTemplateFormatVersion: 2010-09-09
Description: Provisions an ECR repository.

Parameters:
  NamingPrefix:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${NamingPrefix}"
