AWSTemplateFormatVersion: 2010-09-09
Description: Provisions an ECS service infrastructure.
Parameters:
  Environment:
    Type: String
  NamingPrefix:
    Type: String
    Default: Seminar
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/seminar-cf-templates/251f7649ec0637c8152311387126541b.template
      Parameters:
        NamingPrefix:
          Ref: NamingPrefix
        VPCCIDR: 10.0.0.0/16
        PrivateSubnet1CIDR: 10.0.3.0/24
        PrivateSubnet2CIDR: 10.0.4.0/24
        PublicSubnet1CIDR: 10.0.1.0/24
        PublicSubnet2CIDR: 10.0.2.0/24
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/seminar-cf-templates/38a96aaba94a3491576757c421fd4585.template
      Parameters:
        NamingPrefix:
          Ref: NamingPrefix
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPC
  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/seminar-cf-templates/2a2b12396e771d9d9ff771c7c8a3245d.template
      Parameters:
        NamingPrefix:
          Ref: NamingPrefix
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPC
        PublicSubnets:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnets
        LoadBalancerSecurityGroup:
          Fn::GetAtt:
          - SecurityGroups
          - Outputs.LoadBalancerSecurityGroup
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/seminar-cf-templates/49cef9b86be1a05367211f470a9deddb.template
      Parameters:
        NamingPrefix:
          Ref: NamingPrefix
  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - VPC
    - LoadBalancer
    - SecurityGroups
    Properties:
      TemplateURL: https://s3.amazonaws.com/seminar-cf-templates/94370d92a56d8db55644f4b71aa8ea3e.template
      Parameters:
        NamingPrefix:
          Ref: NamingPrefix
        PrivateSubnets:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateSubnets
        ECSSecurityGroup:
          Fn::GetAtt:
          - SecurityGroups
          - Outputs.ECSTaskSecurityGroup
        LoadBalancer:
          Fn::GetAtt:
          - LoadBalancer
          - Outputs.LoadBalancerFullName
        LoadBalancerTargetGroupArn:
          Fn::GetAtt:
          - LoadBalancer
          - Outputs.LoadBalancerTargetGroupArn
